apiVersion: v1
kind: Service
metadata:
	name: my-tomcat-deployment
spec:
	replicas: 3
	selector:
			matchLabels:
				app: my-tomcat
			template:
				metadata:
					labels:
						app: my-tomcat
				spec:
					container: